from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Literal,List
from datetime import datetime

class GeneratorOutput(BaseModel):
    """Structured output for generator and validator agents"""
    generator_answer: str = Field(..., description="The answer generated by the agent")
    generator_source: List[Literal[
    "Summary_of_Product_Characteristics", 
    "Surpass_2", 
    "Surpass_5",
    "Surmount_1",
    "Surmount_5"
]] = Field(..., description="One or more filenames from which generator agent generated the answer.")

class ValidatorOutput(BaseModel):
    """Structured output for generator and validator agents"""
    validator_answer: str = Field(..., description="Answer that is either validated as-is or rewritten by the validator agent based on the context")
    validator_source: List[Literal[
    "Summary_of_Product_Characteristics", 
    "Surpass_2", 
    "Surpass_5",
    "Surmount_1",
    "Surmount_5"
    ]]= Field(..., description='''MUST verify the validator_answer exists filename of the chunk mentioned in the generator_source. 
              Only include filenames where the answer is directly supported by the chunck. 
              Do NOT hallucinate or guess sources. If answer cannot be verified in any file, return empty list.''')



class EmbedChunksResponse(BaseModel):
    db_status: str
    count: int | None = None


class RetrieveChunksRequest(BaseModel):
    query: str


class RetrieveChunksResponse(BaseModel):
    results: list[dict]


class HybridRetrieveResponse(BaseModel):
    results: list[dict]
    params: dict

# Prompt Management Schemas
class PromptBase(BaseModel):
    type: str = Field(..., description="Type: 'generator' or 'validator'")
    template: str = Field(..., description="Prompt template with placeholders like {context}, {question}")
    user_id: str = Field(..., description="User ID who owns this prompt (use 'system' for defaults)")


class UpdatePromptRequest(BaseModel):
    template: str | None = None


class PromptResponse(PromptBase):
    id: int
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class PromptListResponse(BaseModel):
    prompts: list[PromptResponse]
    total: int

class AnswerLanggraphRequest(BaseModel):
    question: str
    file_filter: str | None = Field(None, description="Filter results by filename")
    generator_prompt_id: int | None = Field(None, description="Specific generator prompt ID to use")
    validator_prompt_id: int | None = Field(None, description="Specific validator prompt ID to use")
    user_id: str | None = Field(None, description="User ID for fallback to latest user-specific prompts if prompt IDs not provided")